### ISSUE TITLE
Setup spring boot

### ISSUE THREAD

**Issue by DavidKaczmarek92** [DavidKaczmarek92/WebInsights#19]

**Comment by RahulJadhav16** [comment]
hii David specify your requirements

**Comment by DavidKaczmarek92** [comment]
Hello @RahulJadhav16  For now this task in planning phase. Thank you for this commnet.
I recommend following this project until we create more tasks with `Todo` status 😄

**Comment by sir-braz** [comment]
Hi, can i help you !!

**Comment by DavidKaczmarek92** [comment]
Hello, thank you for this work but we will not allow contributions when we reach beta version.I do not want to waste yours time. For now, everything can change in this project 😄
